### ISSUE TITLE
Now also works with python 3.9.2 on Rpi 4B+ bullseye 64 bits

### ISSUE THREAD

**Issue by Copitano** [akamming/domoticz-watermeter#10]
``
#!/usr/bin/python
import RPi.GPIO as GPIO
import time
import requests
import os

#Watermeter stand (wordt alleen initeel gebruikt als er geen bestand meterstand_water.txt is)
global Counter
Counter = 0

#Domoticz URL
domoticz_url = "http://192.XXX.XX.XXX:8080"
#Domoticz IDX van de water sensor (RFXMeter)
idx = 318

#Open meterstand.txt file en lees meterstand
#Als meterstand.txt niet aanwezig is maakt script bestand aan en vult de meterstand
fn = "/home/pi/domoticz/scripts/meterstand_water.txt"
if os.path.exists(fn):
    f = open(fn, "r+")
    inhoud = f.readline()
    a,b,c = inhoud.split()
    Counter = int(c)
else:
    f = open(fn, "w")
    f.write( 'meterstand = ' + repr(Counter))
    f.close()

#Board is pin nr, BMC is GPIO nr
#Read output from water meter op pin 40
GPIO.setmode(GPIO.BOARD)
# Set GPIO 21 (Pin 40) als Input aditioneel als Pullup-Weerstand aktiveren
GPIO.setup(40, GPIO.IN, pull_up_down = GPIO.PUD_DOWN)

#Functie  callback
#Dit is de functie die aangeroepen wordt in de interrupt
def Interrupt(channel):
    print('Callback function called!')
    time.sleep(0.05)         # need to filter out the false positive of some power fluctuation
    if GPIO.input(40) == 0:
       print('quitting event handler because this was probably a false positive')
       return
    #Teller elke interrupt uitlezen en met 0.5 liter verhogen (deler watermeter op 10 zetten)
    f = open(fn, "r+")
    inhoud = f.readline()
    a,b,c = inhoud.split()
    Counter = int(c)
    Counter = Counter + 1
    f.close()
    #Schrijf meterstand naar bestand
    f = open( fn, 'w')
    f.write( 'meterstand = ' + repr(Counter))
    f.close()
    #Send counter to domoticz JSON
    url1 = domoticz_url+'/json.htm?type=command&param=udevice&idx='+str(idx)+'&svalue='+str(Counter)
    response1 = requests.get(url1).text
    #Voor debug => print voorbeeld van de JSON aanroep en/of de counter
    print ("JSON call = "+ str(url1))
    print ("Watermeter Counter = " + str(Counter))

    #Interrupt-Event toevoegen, sensor geeft een 0 en en bij detectie een 1
#Bij detectie een 1 daarom check stijgende interrupt.
GPIO.add_event_detect(40, GPIO.RISING, callback = Interrupt, bouncetime = 200)

try:
    while True:
      time.sleep(0.2)        
except KeyboardInterrupt:
  GPIO.cleanup()
  print ("\nBye")
``

**Comment by Copitano** [comment]
Sorry i did not succeed putting code right in code `` ``

**Comment by akamming** [comment]
I don’t understand the issue nor the solution

If you have a contribution i much appreciate it, but then pls describe

what was the issue (expected behaviour vs actual behaviour)
Wat was the solution (in Words and pls make a pull request)
How to reproduce so i can test/evaluate

**Comment by Copitano** [comment]
The script worked fine on my 32 bit Pi3B+ with python 2.7 for years. and domoticz version 2022.2
Recently I purchased a Pi4B+. It runs on 64 bit Bullseye with python 3.9.2. and domoticz 2023.1. When I started the script I got the following error:
pi@raspberrypi4:~$ sudo python /home/pi/domoticz/scripts/watermeter.py
   File "/home/pi/domoticz/scripts/watermeter.py", line 61
     print "JSON call = "+ str(url1)
           ^
SyntaxError: invalid syntax
Further research taught me that this is apparently caused by syntax differences between python2 and python3. After the following adjustments in the script, it now also works with python3.
  print "JSON call = "+ str(url1) changed to print("JSON call = "+ str(url1)). The difference is in the parentheses and is adjusted for all print commands.
Then modified: "import urllib2" by "import requests" (urllib2 is no longer supported in python3)
Then replace:
req1 = urllib2.Request(url1)
response1 = urllib2.urlopen(req1)
by: response1 = requests.get(url1).text
and replace:
     f = file(fn, "r+")
     f = open(fn)
by: f = open(fn, "r+")
Now the script also runs on python3 for me.
Incidentally, more people have apparently had this problem. For example [(https://www.domoticz.com/forum/viewtopic.php?p=299030#p299030)] You can make them very happy with the custom script I think.
I'm sorry if I don't quite understand all the rules (what is a pull request?). But I think with a few minor tweaks you can save many people moving to a Pi4 with python3 a lot of headaches and frustration. So meant to help ;-)

**Comment by Copitano** [comment]
@akamming 
I have meen sleeping all the time. Posted the story about a differend script, possibly the one you mention [https://www.domoticz.com/forum/viewtopic.php?f=28&t=17123](url) in your introduction. 
However I did install your plugin, but it didn't work on my new system. Seems like de plugin even didn't start, but no error message.
Sorry to bother you with this.

**Comment by akamming** [comment]
BTW: Just checked: my current installs are all python 3.9.2

if your plugin didn't start and you a no error message then there is another issue: domoticz always logs if it cannot start a plugin. maybre raise your loglevels
