### ISSUE TITLE
Error: (FindModule) Domoticz/DomoticzEx modules not found in interpreter

### ISSUE THREAD

**Issue by piacco** [akamming/domoticz-watermeter#5]
Hi,
I did a fresh install of domoticz with your plugin and i get an error message in the domoticz log. I tink its related to the plugin, the error message that i get is
` Error: (FindModule) Domoticz/DomoticzEx modules not found in interpreter.`

The strange thing is that the plugin is still working.
Can it be related to the new python framework off Domoticz? 

Regards,

Piacco

**Comment by roblomq** [comment]
I also have this error and this plugin installed. I'm searching for the cause of this error for a long time, did a new search recently and found the post above.

**Comment by akamming** [comment]
I have no idea. I am also not on latest beta, but on latest stable. so that might be something.

Seems python itself related..

Can you try on latest stable?

**Comment by piacco** [comment]
Unfortunally i'am can't go back to the stable version, because of the domoticz database i get the message database not backwards compatible. Before the clean install the plugin works like a charm.

I'm not a programmer but maybe this information on the wiki page off Domoticz, can help you 

`Troubleshooting
Importing Modules Fails

Python 'import' that are unsuccessful will stop the entrie plugin from importing and running unless they are wrapped within a 'try'/'except' pair. If a module is not found the Plugin Framework will provide as much information as it gets from Python. For example, an attempt to import fakemodule in a plugin called 'Google Devices' will be reported like this in the Domoticz log:

 2019-03-23 17:17:44.483  Error: (GoogleDevs) failed to load 'plugin.py', Python Path used was '/home/domoticz/plugins/Domoticz-Google-Plugin/:/usr/lib/python36.zip:/usr/lib/python3.6:/usr/lib/python3.6:/usr/lib/python3.6/lib-dynload:/usr/local/lib/python3.6/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.6/dist-packages'.
 2019-03-23 17:17:44.483  Error: (Google Devices) Module Import failed, exception: 'ModuleNotFoundError'
 2019-03-23 17:17:44.483  Error: (Google Devices) Module Import failed: ' Name: fakemodule'
 2019-03-23 17:17:44.483  Error: (Google Devices) Error Line details not available.

the framework shows the directories it searches. Broadly these are: the plugin directory, the existing Python path as picked up when Domoticz started and the 'site' directories for system level modules installed with pip3. Local 'site' directories are not searched by defaul although plugin developers can add any directory the like to the path inside the plugin. Pip3 installs packages in system directories when sudo is used on linux platforms. `

ps.Its not al real a big issue because the plugin is counting my liters off water, but it is a bit annoying, to have these error messages in the domoticz log.

**Comment by akamming** [comment]
this is something else. If the plugin cannot be imported, indeed it will disable the entire plugin. That's not whats happening here. The domoticz .cpp code gives an error and i don't know why...

**Comment by akamming** [comment]
Cannot reproduce on stable
