### ISSUE TITLE
Since update to domoticz 2022.1 there is an error message: (FindModule) Domoticz/DomoticzEx modules not found in interpreter.

### ISSUE THREAD

**Issue by edwinp1** [akamming/domoticz-watermeter#6]

**Comment by edwinp1** [comment]
Since update to domoticz 2022.1 there is an error message: (FindModule) Domoticz/DomoticzEx modules not found in interpreter.
Any chance this can be resolved?
Thx in advance

**Comment by roblomq** [comment]
Why is this issue marked as closed? If I'm right the issue isn't solved yet.

**Comment by edwinp1** [comment]
Closed by accident, find this tool a bit complex :-)

**Comment by edwinp1** [comment]
https://www.domoticz.com/forum/viewtopic.php?p=286251#p286251
