### ISSUE TITLE
Domoticz goes offline

### ISSUE THREAD

**Issue by Jeroenrobbert** [akamming/domoticz-watermeter#9]
good day I have a problem with the plugin I installed a new Domoticz and immediately installed this plugin but as soon as I add the hardware the Domoticz goes offline and can no longer be online tried twice with a completely new installation thanks

**Comment by akamming** [comment]
this is a general issue with domoticz and python plugins.  

just checked. On completely new domoticz install (install pi with default OS, the use default domoticz instructions it works)
